
import "./globals.css";
import { fonts } from './utils/localFonts';
import Header from "./components/header/Header";
import bg_desk from '@/public/images/bg/bg_desk.png';
import Image from 'next/image';
import { detectDevice } from './utils/device';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let device = await detectDevice();



  return (
    <html lang="en">
      <body className={fonts.className}>

        <Header />
        {children}

        {!device && (
          <Image
            src={bg_desk} // Default image
            alt="Descriptive text for the image"
            width={1920}
            height={1558}
            style={{ objectFit: "cover", objectPosition: "center", top: "0", position: "absolute", zIndex: "-1" }}
          />
        )}

      </body>
    </html>
  );
}
